# Generated by Django 5.1.5 on 2025-01-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_address', models.TextField()),
                ('station_capacity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('vat_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_invoice_no', models.CharField(max_length=50)),
                ('charge_invoice_date', models.DateField()),
                ('charge_reference_no', models.CharField(max_length=100)),
                ('price_per_kwh', models.FloatField()),
                ('total_kwh', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('charge_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_crg_backend.chargingstation')),
                ('charge_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_crg_backend.customer')),
            ],
        ),
    ]
