# Generated by Django 5.1.5 on 2025-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_crg_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='station_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='station_capacity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
